Presentation/GymManagement.UI/Models/ErrorViewModel.cs
using System;

namespace GymManagement.UI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Presentation/GymManagement.UI/Models/TrainerMissionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GymManagement.Application.ViewModels.MissionViewModel;
using GymManagement.Application.ViewModels.TrainerViewModel;

namespace GymManagement.UI.Models
{
    public class TrainerMissionViewModel
    {
        public IEnumerable<TrainerQueryViewModel> Trainers { get; set; }
        public IEnumerable<MissionQueryViewModel> Missions { get; set; }

    }
}

Presentation/GymManagement.UI/Controllers/AdminController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using GymManagement.Application.Interfaces.ServiceInterfaces;
using GymManagement.Application.ViewModels.MemberViewModel;
using GymManagement.Application.ViewModels.TrainerViewModel;
using GymManagement.UI.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GymManagement.UI.Controllers
{
    public class AdminController : Controller
    {
        private readonly IManagerService _managerService;
        private readonly ITrainerService _trainerService;
        private readonly IMissionService _missionService;
        private readonly IEquipmentService _equipmentService;
        private readonly IMemberService _memberService;

        public AdminController( IManagerService managerService, ITrainerService trainerService, IMissionService missionService, IEquipmentService equipmentService, IMemberService memberService)
        {
            
            _managerService = managerService;
            _trainerService = trainerService;
            _missionService = missionService;
            _equipmentService = equipmentService;
            _memberService = memberService;
        }

        [HttpPost]
        public async Task<IActionResult> Login(MemberLoginViewModel model)
        {
            if (_memberService.Login(model))
            {
                var claims = new List<Claim>
                {

                    new Claim(ClaimTypes.Email,model.Email)
                };
                var userIdentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                await HttpContext.SignInAsync(principal);

                return RedirectToAction("Dashboard");
            }
            return NotFound();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Dashboard()
        {
           var members =  _managerService.GetAll();

           if (members is null)
           {
               return NotFound();
           }

           return View(members);
        }
        public IActionResult Members()
        {
            var members = _managerService.GetAll();
            return View(members);
        }

        [Authorize]
        public IActionResult Trainers()
        {
            var trainers = _trainerService.GetTrainersWithEmployeeDetail();
            TrainerMissionViewModel model = new TrainerMissionViewModel();
            model.Trainers = _trainerService.GetTrainersWithEmployeeDetail();
            model.Missions = _missionService.GetAll().Take(11);

            return View(model);
        }

        [HttpPost]
        public IActionResult AddTrainer(TrainerCommandViewModel model)
        {
            if (model is not null)
            {
                _managerService.CreateTrainer(model);
            }
            return View("Trainers");
        }

        [HttpGet]
        public IActionResult AddTrainer()
        {
            return View();
        }

        public IActionResult Billign()
        {
            return View();
        }

        public IActionResult Profile()
        {
            return View();
        }

        public IActionResult Equipment()
        {
            var equipments = _equipmentService.GetEquipmentsWithTrainer();

            return View(equipments);
        }
    }
}

Presentation/GymManagement.UI/Controllers/HomeController.cs
using GymManagement.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Linq;
using GymManagement.Application.Interfaces.ServiceInterfaces;


namespace GymManagement.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ICampaignService _campaignService;

        public HomeController(ILogger<HomeController> logger, ICampaignService campaignService)
        {
            _logger = logger;
            _campaignService = campaignService;
        }

        public IActionResult Index()
        {
           var campaigns =  _campaignService.GetAll();
           
            return View(campaigns);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Presentation/GymManagement.UI/Controllers/MemberController.cs
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using GymManagement.Application.Interfaces.ServiceInterfaces;
using GymManagement.Application.ViewModels.MemberViewModel;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;


namespace GymManagement.UI.Controllers
{
    public class MemberController : Controller
    {
        private readonly IMemberService _memberService;

        public MemberController(IMemberService memberService)
        {
            _memberService = memberService;
        }

        public IActionResult Index()
        {
            return View();
            
        }

        [HttpPost]
        public async Task<IActionResult> Login(MemberLoginViewModel model)
        {
            if (_memberService.Login(model))
            {
                var claims = new List<Claim>
                {

                    new Claim(ClaimTypes.Email,model.Email)
                };
                var userIdentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index");
            }

            return NotFound();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
    }
}

Presentation/GymManagement.UI/Views/Admin/AddTrainer.cshtml
@model TrainerCommandViewModel

@{
    ViewData["Title"] = "AddTrainer";
    Layout = "_AdminLayout";
}

<h1>Antrenör Ekle</h1>
<hr />
<h2>Antrenör Bilgilerini Giriniz</h2>
<style>
    .form-row-two {
        display: flex;
        align-content: space-between;
        justify-content: center;
    }
</style>

<form asp-action="AddTrainer" asp-controller="Admin">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">

        <div class="form-row-two">
            <div class="col bg-white p-1" style="width: 40%; border-radius: 10px; margin-right: 10px;">
                <input asp-for="@Model.EmployeeDetail.FirstName" class="form-control text-dark" placeholder="Ad" />
                <span asp-validation-for="@Model.EmployeeDetail.FirstName" class="text-danger"></span>
            </div>
            <div class="col bg-white p-1" style="width: 40%; border-radius: 10px; margin-left: 10px;">
                <input asp-for="@Model.EmployeeDetail.LastName" class="form-control text-dark" placeholder="Soyad" />
                <span asp-validation-for="@Model.EmployeeDetail.LastName" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group" style="margin: 20px 0;">
        <div class="form-row-two">

            <div class="col bg-white p-1" style="width: 40%; border-radius: 10px; margin-right: 10px;">

                <input asp-for="@Model.EmployeeDetail.InsuranceNumber" class="form-control" placeholder="Sosyal güvenlik numarası" />
                <span asp-validation-for="@Model.EmployeeDetail.InsuranceNumber" class="text-danger"></span>
            </div>
            <div class="col bg-white p-1" style="width: 40%; border-radius: 10px; margin-left: 10px;">
                <input type="number" asp-for="@Model.EmployeeDetail.Salary" class="form-control" placeholder="Maaş" />
                <span asp-validation-for="@Model.EmployeeDetail.Salary" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="form-row-two">
            <div class="col bg-white p-1" style="width: 40%; border-radius: 10px; margin-right: 10px;">
                <input type="number" asp-for="@Model.WorkerContract.Duration" class="form-control" placeholder="Sözleşme süresi ay bazında" />
                <span asp-validation-for="@Model.WorkerContract.Duration" class="text-danger"></span>
            </div>
        </div>
    </div>
    <div class="form-group" style="margin: 20px; ">
        <input type="submit" value="Ekle" class="btn btn-primary" style="width: 100%;" />
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");

    }
}

Presentation/GymManagement.UI/Views/Admin/Members.cshtml
@model IEnumerable<GymManagement.Domain.Entities.Member>

@{
    Layout = "_AdminLayout";
}


<div class="card my-4">
    <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
        <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize ps-3">Üyeler</h6>
        </div>
    </div>
    <div class="card-body px-0 pb-2">
        <div class="table-responsive p-0">
            <table class="table align-items-center mb-0">
                <thead>
                    <tr>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Ad-Soyad</th>
                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Borç</th>
                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Ödeme Durumu</th>
                        <th class="text-center text-uppercase text-secondary text-xxs font-weight-bolder opacity-7">Katılma Tarihi</th>
                        <th class="text-uppercase text-secondary text-xxs font-weight-bolder opacity-7 ps-2"></th>
                    </tr>
                </thead>
                <tbody>
                
                @foreach (var member in Model)
                {
                    <tr>
                        <td>
                            @{
                                string adSoyad = @member.FirstName +" "+ member.LastName;
                            }

                            <div class="d-flex flex-column justify-content-center" style="margin-left: 5px;">
                                <h6 class="mb-0 text-sm font-weight-bold">@adSoyad</h6>
                                <p class="text-xs text-secondary mb-0">@member.Email</p>
                            </div>
                        </td>
                        <td  class="align-middle text-center text-sm">
                            <p class="text-xs font-weight-bold mb-0">@member.Debt</p>
                        </td>

                        <td  class="align-middle text-center text-sm">
                            <p class="text-xs font-weight-bold mb-0">@member.NormalizedUserName</p>
                        </td>
                        <td class="align-middle text-center text-sm">

                            @if (@member.IsPaymentStatus)
                             {
                                <p class="badge bg-gradient-success mb-0">Ödendi</p>
                             }
                             else
                             {
                                 <p class="badge bg-gradient-danger mb-0">Ödenmedi</p>
                             }

                        </td>
                        <td class="align-middle">
                            <a href="javascript:;" class="text-secondary font-weight-bold text-xs" data-toggle="tooltip" data-original-title="Edit user">
                                Detay
                            </a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

Presentation/GymManagement.UI/Views/Member/Login.cshtml
@model GymManagement.Application.ViewModels.MemberViewModel.MemberLoginViewModel

@{ Layout = null;}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" sizes="76x76" href="~/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="~/assets/img/favicon.png">
    <title>
        Material Dashboard 2 by Creative Tim
    </title>
    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
    <!-- Nucleo Icons -->
    <link href="~/assets/css/nucleo-icons.css" rel="stylesheet" />
    <link href="~/assets/css/nucleo-svg.css" rel="stylesheet" />
    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <!-- Material Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
    <!-- CSS Files -->
    <link id="pagestyle" href="~/assets/css/material-dashboard.css?v=3.0.1" rel="stylesheet" />
</head>

<body class="bg-gray-200">
    <div class="container position-sticky z-index-sticky top-0">
        <div class="row">
            <div class="col-12">

            </div>
        </div>
    </div>
    <main class="main-content  mt-0">
        <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');">
            <span class="mask bg-gradient-dark opacity-6"></span>
            <div class="container my-auto">
                <div class="row">
                    <div class="col-lg-4 col-md-8 col-12 mx-auto">
                        <div class="card z-index-0 fadeIn3 fadeInBottom">
                            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
                                <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                                    <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">SIGN IN</h4>
                                    <div class="row mt-3">
                                        <div class="col-2 text-center ms-auto">
                                            <a class="btn btn-link px-3" href="javascript:;">
                                                <i class="fa fa-facebook text-white text-lg"></i>
                                            </a>
                                        </div>
                                        <div class="col-2 text-center px-1">
                                            <a class="btn btn-link px-3" href="javascript:;">
                                                <i class="fa fa-github text-white text-lg"></i>
                                            </a>
                                        </div>
                                        <div class="col-2 text-center me-auto">
                                            <a class="btn btn-link px-3" href="javascript:;">
                                                <i class="fa fa-google text-white text-lg"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="card-body">
                                <form role="form" class="text-start" asp-controller="Member" asp-action="Login" >
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="input-group input-group-outline my-3">
                                        <label asp-for="Email" class="form-label">Email</label>
                                        <input asp-for="Email" class="form-control" />
                                        <span asp-validation-for="Email" class="text-danger"></span>
                                    </div>
                                    <div class="input-group input-group-outline mb-3">
                                        <label asp-for="Password" class="form-label">Password</label>
                                        <input type="password" asp-for="Password" class="form-control" />
                                        <span asp-validation-for="Password" class="text-danger"></span>
                                    </div>
                                    <div class="form-check form-switch d-flex align-items-center mb-3">
                                        <input class="form-check-input" type="checkbox" id="rememberMe">
                                        <label class="form-check-label mb-0 ms-2" for="rememberMe">Remember me</label>
                                    </div>
                                    <div class="text-center form-group">
                                        <input type="submit" value="Giriş Yap" class="btn bg-gradient-primary w-100 my-4 mb-2" />
                                    </div>
                                    <p class="mt-4 text-sm text-center">
                                        Don't have an account?
                                        <a href="~/pages/sign-up.html" class="text-primary text-gradient font-weight-bold">Sign up</a>
                                    </p>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="footer position-absolute bottom-2 py-2 w-100">
                <div class="container">
                    <div class="row align-items-center justify-content-lg-between">
                        <div class="col-12 col-md-6 my-auto">
                            <div class="copyright text-center text-sm text-white text-lg-start">
                                ©
                                <script>
                  document.write(new Date().getFullYear())
                                </script>,
                                made with <i class="fa fa-heart" aria-hidden="true"></i> by
                                <a href="https://www.creative-tim.com" class="font-weight-bold text-white" target="_blank">Creative Tim</a>
                                for a better web.
                            </div>
                        </div>
                        <div class="col-12 col-md-6">
                            <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                                <li class="nav-item">
                                    <a href="https://www.creative-tim.com" class="nav-link text-white" target="_blank">Creative Tim</a>
                                </li>
                                <li class="nav-item">
                                    <a href="https://www.creative-tim.com/presentation" class="nav-link text-white" target="_blank">About Us</a>
                                </li>
                                <li class="nav-item">
                                    <a href="https://www.creative-tim.com/blog" class="nav-link text-white" target="_blank">Blog</a>
                                </li>
                                <li class="nav-item">
                                    <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-white" target="_blank">License</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </main>
    <!--   Core JS Files   -->
    <script src="~/assets/js/core/popper.min.js"></script>
    <script src="~/assets/js/core/bootstrap.min.js"></script>
    <script src="~/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="~/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
      var options = {
        damping: '0.5'
      }
      Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
    </script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="~/assets/js/material-dashboard.min.js?v=3.0.1"></script>
</body>

Presentation/GymManagement.UI/Views/Shared/_Layout.cshtml
   
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Gym NA203 | TEMA </title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="~/img/favicon.ico">

    <!-- CSS here -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/slicknav.css">
    <link rel="stylesheet" href="~/css/flaticon.css">
    <link rel="stylesheet" href="~/css/gijgo.css">
    <link rel="stylesheet" href="~/css/animate.min.css">
    <link rel="stylesheet" href="~/css/animated-headline.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="~/css/themify-icons.css">
    <link rel="stylesheet" href="~/css/slick.css">
    <link rel="stylesheet" href="~/css/nice-select.css">
    <link rel="stylesheet" href="~/css/style.css">
</head>

<body class="black-bg">
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="~/img/logo/loder.png" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->
    <header>
        <!-- Header Start -->
        <div class="header-area header-transparent">
            <div class="main-header header-sticky">
                <div class="container-fluid">
                    <div class="menu-wrapper d-flex align-items-center justify-content-between">
                        <!-- Logo -->
                        <div class="logo">
                            <a href="#"><img style="width: 95px; height: 45px;" src="~/img/logo/logo.png" alt=""></a>
                        </div>
                        <!-- Main-menu -->
                        <div class="main-menu f-right d-none d-lg-block">
                            <nav>
                                <ul id="navigation">
                                    <li><a href="#">Ana Sayfa</a></li>
                                    <li><a href="AboutUs.html">Hakkımızda</a></li>
                                    <li><a href="courses.html">Courses</a></li>
                                    <li><a href="pricing.html">Pricing</a></li>
                                    <li><a href="gallery.html">Gallery</a></li>
                                    <li>
                                        <a href="blog.html">Blog</a>
                                        <ul class="submenu">
                                            <li><a href="blog.html">Blog</a></li>
                                            <li><a href="blog_details.html">Blog Details</a></li>
                                            <li><a href="elements.html">Elements</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="contact.html">Contact</a></li>
                                </ul>
                            </nav>
                        </div>
                        <!-- Header-btn -->
                        <div class="header-btns d-none d-lg-block f-right">
                            <a asp-controller="Member" asp-action="Login" class="btn"> Login</a>
                        </div>

                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->
    </header>
<main>
    @RenderBody();
</main>
    <footer>
        <!--? Footer Start-->
        <div class="footer-area black-bg">
            <div class="container">
                <div class="footer-top footer-padding">
                    <!-- Footer Menu -->
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="single-footer-caption mb-50 text-center">
                                <!-- logo -->
                                <div class="footer-logo wow fadeInUp" data-wow-duration="1s" data-wow-delay=".2s">
                                    <a href="#"><img src="~/img/logo/logo2_footer.png" alt=""></a>
                                </div>
                                <!-- Menu -->
                                <!-- Header Start -->
                                <div class="header-area main-header2 wow fadeInUp" data-wow-duration="2s" data-wow-delay=".4s">
                                    <div class="main-header main-header2">
                                        <div class="menu-wrapper menu-wrapper2">
                                            <!-- Main-menu -->
                                            <div class="main-menu main-menu2 text-center">
                                                <nav>
                                                    <ul>
                                                        <li><a href="index.html">Home</a></li>
                                                        <li><a href="about.html">About</a></li>
                                                        <li><a href="courses.html">Courses</a></li>
                                                        <li><a href="pricing.html">Pricing</a></li>
                                                        <li><a href="gallery.html">Gallery</a></li>
                                                        <li><a href="contact.html">Contact</a></li>
                                                    </ul>
                                                </nav>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Header End -->
                                <!-- social -->
                                <div class="footer-social mt-30 wow fadeInUp" data-wow-duration="3s" data-wow-delay=".8s">
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Footer Bottom -->
                <div class="footer-bottom">
                    <div class="row d-flex align-items-center">
                        <div class="col-lg-12">
                            <div class="footer-copy-right text-center">
                                <p>
                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                    Copyright &copy;
                                    <script>
                                        document.write(new Date().getFullYear());
                                    </script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </footer>
    <!-- Scroll Up -->
    <div id="back-top">
        <a title="Go to Top" href="#"> <i class="fas fa-level-up-alt"></i></a>
    </div>


    <script src="~/js/vendor/modernizr-3.5.0.min.js"></script>
    <script src="~/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.slicknav.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/slick.min.js"></script>
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/animated.headline.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>

 
    <script src="~/js/gijgo.min.js"></script>
    <script src="~/js/jquery.nice-select.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>

    <script src="~/js/jquery.counterup.min.js"></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/jquery.countdown.min.js"></script>
    <script src="~/js/hover-direction-snake.min.js"></script>
                 
   
    <script src="~/js/contact.js"></script>
    <script src="~/js/jquery.form.js"></script>
    <script src="~/js/jquery.validate.min.js"></script>
    <script src="~/js/mail-script.js"></script>
    <script src="~/js/jquery.ajaxchimp.min.js"></script>
                 

    <script src="~/js/plugins.js"></script>
    <script src="~/js/main.js"></script>

</body>

</html>